universe:
  - 4
  - 2
  - 7
  - 1
  - 12
  - 6
  - 11
  - 15
  - 21
  - 65
  - 54
  - 10
  - 43
  - 34
  - 63

sets:
  - - 1
    - 2
    - 7
    - 63
  - - 1
    - 6
  - - 11
    - 6
  - - 7
    - 12
  - - 2
    - 4
    - 34
  - - 65
    - 43
    - 21
  - - 10
    - 1
  - - 65
    - 21
    - 7
    - 2
  - - 21
    - 15
  - - 11
    - 10
    - 1
  - - 54
    - 6
    - 34