universe:
  - 4
  - 2
  - 7
  - 1
  - 12
  - 6
  - 11
  - 15
  - 21
  - 65
  - 54
  - 10
  - 43
  - 34
  - 63
  - 105
  - 110
  - 154
  - 94
  - 15
  - 431
  - 200
  - 199
  - 166


sets:
  - - 1
    - 2
    - 63
  - - 1
    - 6
  - - 11
    - 6
  - - 7
    - 12
  - - 2
    - 4
    - 34
  - - 65
    - 43
    - 21
  - - 10
    - 1
  - - 65
    - 21
    - 7
    - 2
  - - 21
    - 15
  - - 11
    - 10
    - 1
  - - 54
    - 6
    - 34
    - 105
  - - 110
    - 21
    - 431
    - 2
    - 7
  - - 154
    - 6
    - 1
  - - 94
    - 10
    - 6
    - 1
  - - 15
    - 34
    - 21
  - - 200
    - 105
    - 94
    - 65
  - - 431
    - 10
    - 7
  - - 199
    - 6
    - 2
    - 10
  - - 166
    - 4
  - - 94
    - 2
    - 7
  - - 21
    - 15
  - - 166
    - 4
  - - 431
    - 11